# The uptime sensor allows you to track the time the ESP has stayed up for in seconds. 
# https://esphome.io/components/sensor/uptime.html
platform        : uptime
name            : "${devicelocation} Uptime Sensor"
update_interval : 60s
