####################################################
#                                                  #
#                  AUTOMATIONS                     #
#                                                  #
####################################################

title          : Automations

cards:
  - type       : entities
    title      : Automation Modes
    show_header_toggle: false
    entities:
      - entity : input_boolean.vacation_mode
      - entity : input_boolean.privacy_mode
      - entity : input_boolean.guest_mode
      - entity : input_boolean.test_input1
      - entity : input_boolean.test_input2
      - entity : input_boolean.test_input3
       
#  - type       : entities
#    show_header_toggle: false
#    title      : Zigbee2mqtt
#    entities:
#      - entity : sensor.zigbee2mqtt_bridge_state
#      - entity : sensor.zigbee2mqtt_version
#      - entity : sensor.coordinator_version
#      - entity : input_select.zigbee2mqtt_log_level
#      - type   : divider
#      - entity : switch.zigbee2mqtt_main_join
#      - entity : timer.zigbee_permit_join
#      - type   : divider
#      - entity : input_text.zigbee2mqtt_old_name
#      - entity : input_text.zigbee2mqtt_new_name
#      - entity : script.zigbee2mqtt_rename
#      - type   : divider
#      - entity : input_text.zigbee2mqtt_remove
#      - entity : script.zigbee2mqtt_remove

#  - type       : entities
#    title      : Automations - System
#    show_header_toggle: true
#    entities:
#      - entity : automation.system_delayed_start_automations
#        icon   : mdi:robot
