####################################################
#                                                  #
#                  AUTOMATIONS                     #
#                                                  #
####################################################

title          : Automations

cards:
  - type       : entities
    title      : Automation Modes
    show_header_toggle: false
    entities:
      - entity : input_boolean.vacation_mode
      - entity : input_boolean.privacy_mode
      - entity : input_boolean.guest_mode
      - entity : input_boolean.test_input1
      - entity : input_boolean.test_input2
      - entity : input_boolean.test_input3

#  - type       : entities
#    title      : Automations - System
#    show_header_toggle: true
#    entities:
#      - entity : automation.system_delayed_start_automations
#        icon   : mdi:robot
