# Shelly 1 device
# Output is constantly high (for when a Hue bulb is attached)

esphome:
  name        : $devicename
  platform    : ESP8266
  board       : esp01_1m
  on_boot:
    priority  : -10
    then:
      - switch.turn_on: switch_output

<<: !include common.yaml

text_sensor:
  - !include text_sensors/version.yaml

sensor:
  - !include sensors/uptime.yaml
  - !include sensors/wifi_signal.yaml

binary_sensor:
  - platform             : gpio
    pin                  : GPIO5
    name                 : "${devicelocation} Switch"
    filters:
      - delayed_on       : 10ms
      - delayed_off      : 10ms
      
  - !include binary_sensors/status.yaml

switch:
  - platform             : output
    name                 : "${devicelocation} Light Power"
    output               : 'relay_output'
    id                   : switch_output

  - !include switches/restart.yaml

output:
  - platform             : gpio
    pin                  : GPIO4
    id                   : relay_output
