automation              : !include_dir_merge_list ../automations
automation fromfrontend : !include ../automations.yaml

#fromfrontend keyword does nothing. this is a trick to load multiply automation sources/files.
