#################################################################
## Zigbee2MQTT
#################################################################

# Input select for Zigbee2mqtt debug level
input_select:
  zigbee2mqtt_log_level:
    name           : Zigbee2mqtt Log Level
    initial        : info
    icon           : mdi:format-list-bulleted
    options:
     - debug
     - info
     - warn
     - error

# Input text to input Zigbee2mqtt friendly_name for scripts
input_text:
  zigbee2mqtt_old_name:
    name           : Old Name
  zigbee2mqtt_new_name:
    name           : New Name
  zigbee2mqtt_remove:
    name           : Remove device

# Scripts for renaming & removing devices
script:
  zigbee2mqtt_rename:
    alias          : Zigbee2mqtt Rename
    sequence:
      service      : mqtt.publish
      data_template:
        topic      : zigbee2mqtt/bridge/config/rename
        payload_template: >-
          {
            "old": "{{ states.input_text.zigbee2mqtt_old_name.state | string }}",
            "new": "{{ states.input_text.zigbee2mqtt_new_name.state | string }}"
          }
  zigbee2mqtt_remove:
    alias          : Zigbee2mqtt Remove
    sequence:
      service      : mqtt.publish
      data_template:
        topic      : zigbee2mqtt/bridge/config/remove
        payload_template: "{{ states.input_text.zigbee2mqtt_remove.state | string }}"


sensor:
  # Sensor for monitoring the bridge state
  - platform       : mqtt
    name           : Zigbee2mqtt Bridge state
    state_topic    : "zigbee2mqtt/bridge/state"
    icon           : mdi:router-wireless
  # Sensor for Showing the Zigbee2mqtt Version
  - platform       : mqtt
    name           : Zigbee2mqtt Version
    state_topic    : "zigbee2mqtt/bridge/config"
    value_template : "{{ value_json.version }}"
    icon           : mdi:zigbee
  # Sensor for Showing the Coordinator Version
  - platform       : mqtt
    name           : Coordinator Version
    state_topic    : "zigbee2mqtt/bridge/config"
    value_template : "{{ value_json.coordinator }}"
    icon           : mdi:chip

# Switch for enabling joining
switch:
  - platform       : mqtt
    name           : "Zigbee2mqtt Main join"
    state_topic    : "zigbee2mqtt/bridge/config/permit_join"
    command_topic  : "zigbee2mqtt/bridge/config/permit_join"
    payload_on     : "true"
    payload_off    : "false"

