- id: '1593942143522'
  alias: Nieuwe automatisering
  description: ''
  trigger:
  - device_id: 5bcf8a334a1040c0ba0354846f6e7282
    domain: zha
    platform: device
    subtype: left
    type: device_rotated
  condition: []
  action:
  - device_id: 6bd5df9f1fad4e30ab212028119aa2bc
    domain: light
    entity_id: light.living_room_tv_desk
    type: brightness_decrease
- id: '1593942191267'
  alias: Nieuwe automatisering2
  description: ''
  trigger:
  - device_id: 5bcf8a334a1040c0ba0354846f6e7282
    domain: zha
    platform: device
    subtype: right
    type: device_rotated
  condition: []
  action:
  - device_id: 6bd5df9f1fad4e30ab212028119aa2bc
    domain: light
    entity_id: light.living_room_tv_desk
    type: brightness_increase
- id: '1593942225138'
  alias: Nieuwe automatisering
  description: ''
  trigger:
  - device_id: 5bcf8a334a1040c0ba0354846f6e7282
    domain: zha
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition: []
  action:
  - device_id: 6bd5df9f1fad4e30ab212028119aa2bc
    domain: light
    entity_id: light.living_room_tv_desk
    type: toggle
