substitutions:
  devicename     : "esp32cam_1"
  devicelocation : "ESP32Cam 1"
  ip_address     : !secret ip_address_esp32cam1

esphome:
  name        : $devicename
  platform    : ESP32
  board       : esp32dev
# board       : esp-wrover-kit  # alternative board

wifi:
  ssid        : !secret wifi_ssid
  password    : !secret wifi_password
  ap:
    ssid      : "${devicelocation} Fallback Hotspot"
    password  : !secret wifi_fallback_password
  manual_ip:
    static_ip : ${ip_address}
    gateway   : !secret gateway_ip
    subnet    : 255.255.255.0

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Enable Web server.
web_server:
  port        : 80

# Sync time with Home Assistant.
time:
  - platform        : homeassistant
    id              : homeassistant_time

sensor:
  # Sensors with general information.
  - platform        : uptime
    name            : "${devicelocation} Uptime Sensor"
    update_interval : 60s

  - platform        : wifi_signal
    name            : "${devicelocation} WiFi Signal"
    update_interval : 60s

switch:
  # Switch to restart the plug
  - platform        : restart
    name            : "${devicelocation} Restart"
  # Flash light of camera
  - platform        : gpio
    pin             : GPIO4
    name            : "${devicelocation} Flash"

# Uses the red LED as a status indicator
status_led:
  pin:
    number          : GPIO33  # Red led output
    inverted        : true

# Info here: https://esphome.io/components/esp32_camera.html
esp32_camera:
  external_clock:
    pin             : GPIO0
    frequency       : 20MHz
  i2c_pins:
    sda             : GPIO26
    scl             : GPIO27
  data_pins         : [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin         : GPIO25
  href_pin          : GPIO23
  pixel_clock_pin   : GPIO22
  power_down_pin    : GPIO32

  # Image settings
  name              : Image
