substitutions:
  devicename     : "powerplug_1"
  devicelocation : "Living Room Charging Station Outlet"
  # Higher value gives lower watt readout
  current_res    : '0.00290'
  # Lower value gives lower voltage readout
  voltage_div    : '940'
  ip_address     : !secret ip_address_powerplug1

<<: !include .powerplug_base.yaml