substitutions:
  devicename     : "shelly_4"
  devicelocation : "First Floor Landing"
  ip_address     : !secret ip_address_shelly4

globals:
  - id              : use_output
    type            : bool
    restore_value   : true    # output relay should be constantly high.
    initial_value   : 'true'

<<: !include shared/device_shelly_detached_output.yaml
