substitutions:
  devicename     : "shelly_6"
  devicelocation : "Second Floor Landing"
  ip_address     : !secret ip_address_shelly6

globals:
  - id              : use_output
    type            : bool
    restore_value   : false   # output relay is not connected to anything.
    initial_value   : 'false'

<<: !include shared/device_shelly_detached_output.yaml
